---
title: "PSY 8960 Week 8 Project"
author: "Joy Zhou"
output: html_notebook
---

### Reproducible Image and Online Resources
##### An image of this project as of *`r format(Sys.time(), '%d %B %Y')`* can be accessed by clicking this link.
##### An interactive web app is available by clicking this link instead.

### Script Settings and Resources
```{r, message = FALSE, warning = FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(knitr)
library(DT)
```

### Data Import and Cleaning
```{r}
week8_tbl <- read_csv(file = "data/week3.csv") %>%
  mutate(q5 = recode(q5, "1" = 5, "2" = 4, "4" = 2, "5" = 1)) %>%
  select(starts_with("q"))
```

### Visualization
```{r, echo = FALSE, warning = FALSE}
datatable(week8_tbl) 

week8_tbl %>%
  mutate(q1_q6_mean = rowMeans(select(week7_tbl, q1:q6)),
         q8_q10_mean = rowMeans(select(week7_tbl, q8:q10))) %>%
  ggplot(aes(q1_q6_mean, q8_q10_mean)) +
  geom_point(position = "jitter") +
  geom_smooth(method = "lm", color = "purple")
```



